### PR TITLE
fix/feat: fix logical flow error in search query and add notify when …

### PR DESCRIPTION
**Pull request by washonrails**
Fixing logical error in mpv.lua file in line 150. 

```
Error detected to process VimEnter Autocommands for "*":
Error executing lua callback: /home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: unexpected event
stack traceback:
	[C]: in function 'nvim_create_autocmd'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:40: in function 'display'
	/home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:180: in function </home/iamwash/.local/share/nvim/lazy/veil.nvim/lua/veil.lua:178>
E5108: Error executing lua: /home/iamwash/.local/share/nvim/lazy/mpv.nvim/lua/mpv.lua:156: attempt to concatenate local 'query' (a nil value)
stack traceback:
	/home/iamwash/.local/share/nvim/lazy/mpv.nvim/lua/mpv.lua:156: in function 'on_confirm'
	/usr/share/nvim/runtime/lua/vim/ui.lua:95: in function 'input'
	/home/iamwash/.local/share/nvim/lazy/mpv.nvim/lua/mpv.lua:149: in function </home/iamwash/.local/share/nvim/lazy/mpv.nvim/lua/mpv.lua:142>

```
Add a notify when query is not provided.
Add rounded borders ("optional").

Follow image below

Not fixed:
Captura de tela de 2023-03-24 03-13-44
Captura de tela de 2023-03-24 03-14-12

Fixed:

Captura de tela de 2023-03-24 03-15-03

btw thanks for the notes in code :)

### CODE REVIEW

**Comment by tamton-aquib** [comment]
Heyyo @washonrails, thanks for the PR. Will check in the coming days 👍🏻

**Comment by tamton-aquib** [comment]
Hi @washonrails,
I was not here for some time so couldn't get a chance to look at this.

Is there still an issue? Looks like the whole code has changed due to formatting, so I couldn't really check 😅 .

Also uh looks like you've deleted the whole readme.

**Comment by washonrails** [comment]
Hey @tamton-aquib,

I hope you're doing well! I wanted to bring up an important issue regarding the code you're working on. It seems that the version of Lua you're currently using in your code is either version 5.2 or an earlier version. I thought you'd like to know that we've progressed to Lua version 5.4, and there have been some notable changes to the language since then.

Specifically, there's a slight hiccup around line 28 in your code. It appears that the code change has had a minimal impact on the line, but it has led to a plugin-breaking error. To elaborate, the issue arises from the method used to unpack a table. Previously, the line looked like this:

```lua
local time1, time2 = unpack(vim.split(state.timing, ' / '))
```

However, in the current version (5.4) of Lua, the correct syntax to unpack a table has evolved to:

```lua
local time1, time2 = table.unpack(vim.split(state.timing, ' / '))
```

Additionally, I noticed a slight inaccuracy in the documentation regarding the dependency "youtube-dl." The code, specifically on line 112, references a command "ytdl" sourced from the "yt-dlp" dependency, which is installed using pip3. It's worth mentioning that this dependency could lead to a silent error. In particular, certain versions of Linux (such as Ubuntu 22.04) might come with outdated versions of this dependency.

For seamless functionality, it's imperative that both the code and the user's machine are using the same version of the dependency. This applies to both the code querying process and the user's environment. I highly recommend ensuring that both the code and the user's system are running the latest version of the dependency to avoid any potential errors.

Resume: 

Language Version Update:

- Your current code utilizes Lua version 5.2 or an earlier version.
- The latest version of Lua is 5.4, which introduces several changes to the language.
- Around line 28, there's a minor change that has impacted the code and caused a plugin-breaking error.
- Previously, unpacking a table was done using unpack(), but in Lua 5.4, the correct syntax is table.unpack().

<hr>

The documentation mentions a dependency called "youtube-dl."
- Dependency Issue: "youtube-dl" !== "yt-dlp":
  - However, in the code (line 112), there's a reference to the command "ytdl," which comes from the "yt-dlp" dependency.
- "yt-dlp" is installed using pip3 and can lead to silent errors, especially on systems with outdated dependencies.
- Some Linux versions, like Ubuntu 22.04 LTS, might have outdated "yt-dlp" versions.

PS: FORGIVE ME FOR DELETING README.MD 🙏🏼 



Best regards,
[washonrails]

**Comment by tamton-aquib** [comment]
Heyyo @washonrails, thanks for the great explanation!

Regarding the lua version issue, this is what was mentioned in `:help lua-compat`:
> Lua 5.1 is the permanent interface for Nvim Lua.  Plugins need only consider
Lua 5.1, not worry about forward-compatibility with future Lua versions

Also on line 65 in this PR, I cant seem to find any changes 🤔 (its just `unpack()`). Everywhere in the neovim codebase they've used `unpack()` too I believe.

---

Regarding the yt-dlp dependency issue:
Yes, I completely forgot that seems to be the case, will have to update readme.

---

1. The readme is still not there, can you add it back? 😬 
2. It seems like you have changed the height value from 5 to 3, any reasons? 🤔 
3. Regarding the borders too, i think its best to set it to 'single' and leave it to the users to configure.
4. You have changed the command from `MpvToggle` to `Play`.  You haven't mentioned any reasons for that too.

**Comment by washonrails** [comment]
Heyyo @tamton-aquib 

> Also on line 65 in this PR, I cant seem to find any changes 🤔 (its just unpack()). Everywhere in the neovim codebase they've used unpack() too I believe.

I understood. this was just a small problem , however I recommend you to add githubactions here in this repository , it checks for any broken dependencies or updates in the language itself that is being used in the repository , find out about it because it can get rid of small annoying problems like this , believe me if you want this action can be specified to run both daily, weekly, monthly .. it already does all the boring part like , create a pull-request explaining what was changed in the code, then it's up to you to analyze and do what merge.

<hr>

> Regarding the yt-dlp dependency issue:
> Yes, I completely forgot that seems to be the case, will have to update readme.

Now about the case of the "yt-dlp" dependency, it was more annoying because I really thought it was that "youtube-dl" but that's when I had to research more deeply about each one of them and I saw that they are a little different, I really only I noticed that I was using the wrong dependency for the query on line 112, haha!

<hr>

Now answering your questions...

> The readme is still not there, can you add it back? 😬
A: I honestly don't know if I'm going to get that readme back because when I first forked and opened the issue (about 5-6 months ago)

i was using Void Linux system which i accidentally corrupted unintentionally , since then i have been going through other distros like NixOS , Windows , and currently Ubuntu 22.04 JellyFish , probably the README you are looking for was on Void Linux which got corrupted but I'm going to look through some commits I made back then to see if I've saved any parts of it yet.. (SINCERELY FORGIVE ME)

> It seems like you have changed the height value from 5 to 3, any reasons? 🤔

A: In fact, I'll tell you that I changed it because of some bugs I had, like for example, the mouse click didn't work when I clicked on the buttons, and in correlation with this problem of "unpack" the code of the lines
28 to 43 , they were throwing an error where it said that they were not able to convert a table and therefore empty (something like I said above about the problem) so I had to remove them then it started working normally again , in fact I tell you again that it would be better to remove some lines that are redundant in your code , because when it comes to plugins , the cleaner the code the easier and more performant it will be to be maintained by other devs and included in other neovim distributions , like mine for example :D

> Regarding the borders too, i think its best to set it to 'single' and leave it to the users to configure.
A: 
I completely agree, currently HydraVim (my neovim distro) uses a system that allows the user's own configuration where it separates the "user" from the "server", in this system that we have, the user already comes with some essential plugins for the operation and development of the editor, however with one command it generates a whole configuration to the part where it allows to add more plugins and configure them as they wish, and best of all, every configuration that he makes will be saved in github, so he will be exempt from losing all his config and its plugins.

> You have changed the command from MpvToggle to Play. You haven't mentioned any reasons for that too.

A: Ah of course! so boy how do i talk..

it seems the plugin doesn't have a "friendly" command to start it" at least not that i knew until (5-6 months ago)

the reason was just for productivity, for example, before I had to do the command "lua require('mpv').toggle_player" to actually open the music player so I created a command that by typing :MpvToggle it executes that command up and boom! opens the player.. but that was just an optional command of mine, but I strongly recommend having a command that opens without typing "lua require('mpv').toggle_player" every time you want to listen to a song, in fact I even recommend creating it a keybind for that.

PS: If you already have a command for this, I'm sorry again, because I only tried to correct the errors haha!

Thanks buddy ! hugs !!

**Comment by tamton-aquib** [comment]
Heyyo @washonrails,

I have pushed some major refactored code so everything should be fixed. Is this pr safe to be closed?

**Comment by washonrails** [comment]
> Heyyo @washonrails,
> 
> I have pushed some major refactored code so everything should be fixed. Is this pr safe to be closed?

Heyyo ! @tamton-aquib  

OH YEAH BABY , I THINK SO !
The music player is very smooth bro , GREAT JOB 👍🏼 👍🏼 
+1 Follower , It would be an honor if you followed me back ! Inspiration.

**Comment by tamton-aquib** [comment]
> The music player is very smooth bro , GREAT JOB

Thanks 😅 

>  +1 Follower , It would be an honor if you followed me back ! Inspiration.

Thanks, I just followed back too 👍🏻

**Pull request closed without merging**
